name = "portfolio-alexis"
compatibility_date = "2025-03-18"
pages_build_output_dir = ".output/public"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }