name = "portfolio-alexis"
compatibility_date = "2025-03-18"
pages_build_output_dir = ".output/public"

[env.production]
vars = { ENVIRONMENT = "production" }
# Add RESEND_API_KEY as a secret using: wrangler pages secret put RESEND_API_KEY

[env.preview]
vars = { ENVIRONMENT = "preview" }
# Add RESEND_API_KEY as a secret using: wrangler pages secret put RESEND_API_KEY