name = "portfolio-alexis-robin"
compatibility_date = "2025-03-18"

[build]
command = "npm run cf:build"

[site]
bucket = ".output/public"
pages_build_output_dir = ".output/public"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }